server:
  port: 4060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    answer:
      path: /answer/**
      serviceId: answer-service
    employee:
      path: /employee/**
      serviceId: employee-service
    question:
      path: /question/**
      serviceId: question-service
